// https://docs.expo.dev/guides/using-eslint/
const { defineConfig } = require('eslint/config');
const expoConfig = require('eslint-config-expo/flat');

module.exports = defineConfig([
  expoConfig,
  {
    ignores: [
      'dist/*',
      // Generated by Expo Router and gitignored.
      '.expo/**',
      // Deno, not React Native. These import over https:// and run on Deno
      // globals, neither of which this config's resolver can follow - every
      // line of them reported import/no-unresolved. Every test in this repo
      // is currently a Deno test; an RN test would want linting, so narrow
      // this if one ever lands.
      'supabase/functions/**',
      '**/*.test.ts',
    ],
  },
  {
    rules: {
      // All 56 hits were apostrophes and quotes in user-facing copy, which
      // <Text> renders correctly. The stray > and } that this rule genuinely
      // protects against appear nowhere in this codebase.
      'react/no-unescaped-entities': 'off',
    },
  },
]);
